### ISSUE TITLE
Servidor HTTP

### ISSUE THREAD

**Issue by claudiobastos** [dose-na-nuvem/toll-station#5]
- [ ] definiçao de rota
- [ ] definição do esquema de entrada
- [ ] definição do esquema de resposta
- [ ] testes

Sugestão:
rota: /api/v1/traffic
input schema: {tag: idtag}
output schema: {traffic: allowed/denied}

**Comment by luizgribeiro** [comment]
Atribui à mim, por gentileza ;)

**Comment by claudiobastos** [comment]
Concluídos com o PR do @luizgribeiro 👍🏽
